### DISCUSSION TITLE
New Tidal Plugin

### DISCUSSION THREAD

**Discussion by GioF71** [GioF71/upmpdcli-docker#281] [Announcements]
Starting with release 2023-09-16, we have access to the new Tidal Plugin.
See [version history](https://github.com/GioF71/upmpdcli-plugins/blob/master/src/mediaserver/cdplugins/tidal/release.md).
It might be helpful to always add the option for downloading the upstream version of the plugin code.
Here is a simple docker-compose file for a media server configuration:

```
---
version: "3"

services:
  upmpdcli:
    image: giof71/upmpdcli
    container_name: upmpdcli-tidal
    network_mode: host
    environment:
      - RENDERER_MODE=NONE
      - FRIENDLY_NAME=Tidal (upmpdcli)
      - TIDAL_ENABLE=yes
      - TIDAL_TOKEN_TYPE=${TIDAL_TOKEN_TYPE}
      - TIDAL_ACCESS_TOKEN=${TIDAL_ACCESS_TOKEN}
      - TIDAL_REFRESH_TOKEN=${TIDAL_REFRESH_TOKEN}
      - TIDAL_EXPIRY_TIME=${TIDAL_EXPIRY_TIME}
      - TIDAL_AUDIO_QUALITY=${TIDAL_AUDIO_QUALITY:-LOSSLESS}
      - TIDAL_DOWNLOAD_PLUGIN=yes
      - TIDAL_PLUGIN_BRANCH=latest-tidal
    volumes:
      - ./cache:/cache
    restart: unless-stopped
```

The tokens can be generated using an entrypoint of this container image. See [this](https://github.com/GioF71/upmpdcli-docker/blob/main/README.md#obtain-tidal-credentials) section of the documentation.

If your plan allows more than 16bi/44kHz, please specify `HI_RES` or `HI_RES_LOSSLESS` for the TIDAL_AUDIO_QUALITY variable. If you want to allow mp3 320 or lower quality as the maximum (I believe this is quite unlikely), you will need to set the value to `HIGH` or `LOW` respectively.

Edit: we are not in preview mode anymore!
