### ISSUE TITLE
[QUESTION] /waiting

### ISSUE THREAD

**Issue by fr2lancer** [GioF71/upmpdcli-docker#423]
**Describe the bug**
Actually it might not a bug. I more likely I want to know this.

I have setup this docker on top of the moode audio. And let uprcl read my local(same as moode audio resides) directory's sound files and activate upnp renderer on moode audio. And it seems to working fine with mconnect. (good!)

And there is playlist remains in the UI of moode after playing. and it displays as 

![image](https://github.com/GioF71/upmpdcli-docker/assets/6251051/0f79f8ba-6e17-43ca-b326-be17062a9820)

It is okay as moode audio dropped function of browsing of upnp.

However I wanted to know where '/waiting' url has been given to moode audio?
I can't find it in the source code of moode audio and I also can't find in it.

```
python3 /usr/share/upmpdcli/cdplugins/uprcl/uprcl-app.py inside of the docker.
```

I made connection 9090 through docker by opening port in docker-compose and UPRCL_HOSTPORT=localhost:9090 in it.
when I test it with curl localhost:9090. it was able to check networking was going in it.

Is that a protocol of upnp?

or uprcl didn't complete the implementation of all of upnp(if it needed)?

Thank you.
 

% I found this after this ticket - 'cache/metacache' file has this content. where this xml came from ..?
```

cache/metacache:http://192.168.1.23:9090/waiting=<?xml version%3D"1.0" encoding%3D"utf-8"?><DIDL-Lite xmlns:dc%3D"http://purl.org/dc/elements/1.1/
" xmlns:upnp%3D"urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns%3D"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dlna%3D"urn:schemas-dlna-org
:metadata-1-0/"><item id%3D"mpdid:16427" parentID%3D"0" restricted%3D"1" searchable%3D"0"><dc:title>Initializing...</dc:title><orig>mpd</orig><upn
p:class>object.item.audioItem.musicTrack</upnp:class><res>http://192.168.1.23:9090/waiting</res></item></DIDL-Lite>
```

**Operating system(please complete the following information):**
 - OS: [e.g. Raspbian, Debian, Ubuntu, etc]: debian(maybe)
 - Architecture [e.g. armhf, arm64, amd64]: arm64
 - Version [any relevant information]

**Comment by GioF71** [comment]
Hello, can you post your docker-compose file or docker-run command?
Thank you

**Comment by GioF71** [comment]
From what I see without the compose file, it looks to me that "UPRCL_HOSTPORT=localhost:9090" is not ok, because probably a request with the ip address would not be served. Maybe replace localhost with your "192.168.1.23:9090"

**Comment by fr2lancer** [comment]
```
version: "3"                                                                                                                                      
services:                                                                                                                                         
  upmdcli:                                                                                                                                        
    image: giof71/upmpdcli                                                                                                                        
    container_name: upmpdcli-library                                                                                                              
    network_mode: host                                                                                                                            
    environment:                                                                                                                                  
    - PORT_OFFSET=0                                                                                                                               
    - PUID=1000                                                                                                                                   
    - PGID=1000                                                                                                                                   
    - RENDERER_MODE=BOTH                                                                                                                          
    - UPRCL_ENABLE=yes                                                                                                                            
    - UPRCL_USER=upmmpdcli-library                                                                                                                
    - UPRCL_AUTOSTART=1                                                                                                                           
    - UPRCL_HOSTPORT=localhost:9090                                                                                                               
    ports:                                                                                                                                        
    - "9090:9090"            #it seems to not useful when  network_mode: host                                                                                                    
    volumes:                                                                                                                                      
    - ./cache:/cache                                                                                                                              
    - ./log:/log                                                                                                                                  
    - /media/103F0F09103F0F09/:/uprcl/mediadirs/                                                                                                  
#- ./config/uprclconfdir:/urpcl/confdir                                                                                                           
#- ./config/upmpdcli/additional-radio.txt:/user/config/additional-radio.txt                                                                       
    labels:                                                                                                                                       
    - com.centurylinklabs.watchtower.enable=false                                                                                                 
    restart: unless-stopped 
```
/usr/share/upmpdcli/cdplugins/uprcl/uprcl-app.py  : seems like listing 9090 port
