### ISSUE TITLE
[BUG] dlna not showing on network

### ISSUE THREAD

**Issue by Gibbz** [GioF71/upmpdcli-docker#450]
**Describe the bug**
No dlna devices are showing on the network. Are there any special steps required to get this to work? Such as install avahi?

**Docker-compose.yaml file**
```
services:
  upmpdcli:
    image: giof71/upmpdcli
    container_name: upmpdcli
    environment:
      - PUID=1000
      - PGID=1000
      - STARTUP_DELAY_SEC=2
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HOME}/Docker/upmpdcli/upmpdcli.conf:/app/conf/upmpdcli.conf
      - /etc/localtime:/etc/localtime:ro

```

**Additional context**
```
#logfilename =
#loglevel = 2
#pkgdatadir=/usr/share/upmpdcli
#pidfile = /var/run/upmpdcli.pid
#upnpiface = UPNPIFACE
#upnpip =
#upnpport = UPNPPORT
#useipv6 = false
friendlyname = living
avfriendlyname = living av
upnpav = 1
openhome = 1
#lumincompat = 0
#ohinfotexttodata = 0
#saveohcredentials = 1
#checkcontentformat = 1
#opensslcmd =
#iconpath = /usr/share/upmpdcli/icon.png
#cachedir = /var/cache/upmpdcli
#presentationhtml = /usr/share/upmpdcli/presentation.html
#enablel16 = true
mpdhost = localhost
#mpdport = MPD_PORT
#mpdpassword =
#mpdtimeoutms = 2000
#ownqueue = 1
#onstart =
#onplay =
#onpause =
#onstop =
#onstandby =
#externalvolumecontrol =
#getexternalvolume =
#onvolumechange =
#avtautoplay = 0
#ohproductroom = Main Room
radiolist = /app/conf/radiolist.conf
#radioscripts = /usr/share/upmpdcli/radio_scripts
#ohmanufacturername = UpMPDCli heavy industries Co.
#ohmanufacturerinfo = Such nice guys and gals
#ohmanufacturerurl = http://www.lesbonscomptes.com/upmpdcli
#ohmanufacturerimageuri =
#ohmodelname = UpMPDCli UPnP-MPD gateway
#ohmodelinfo =
#ohmodelurl = http://www.lesbonscomptes.com/upmpdcli
#ohmodelimageuri =
#ohproductname = Upmpdcli
#ohproductinfo =
#ohproducturl =
#ohproductimageuri =
#ohmetapersist = 1
#ohmetasleep = 0
#msfriendlyname = MEDIA_SERVER_FRIENDLY_NAME
#plgmicrohttphost = PLG_MICRO_HTTP_HOST
#plgmicrohttpport = PLG_MICRO_HTTP_PORT
#plgproxymethod = redirect
#msiconpath = /usr/share/upmpdcli/icon.png
#hrauser = your hra user name
#hrapass = your Hra password
#hralang = en
#spotifyuser = me@some.place
#spotifypass = agoodpassword
#spotifybitrate = 160
#tidaluser = TIDAL_USERNAME
#tidalpass = TIDAL_PASSWORD
#tidalapitoken = TIDAL_API_TOKEN
#tidalquality = TIDAL_QUALITY
#qobuzuser = QOBUZ_USERNAME
#qobuzpass = QOBUZ_PASSWORD
#qobuzformatid = QOBUZ_FORMAT_ID
#deezeruser = me@some.place
#deezerpass = agoodpassword
#uprcluser = UPRCL_USER
#uprcltitle = UPRCL_TITLE
#uprclhostport = UPRCL_HOSTPORT
#uprclconfdir = /uprcl/confdir
#uprclconfrecolluser = /user/config/recoll.conf.user
#uprclminimconfig =
#uprclmediadirs = /uprcl/mediadirs
#uprclpaths =
#uprclautostart = UPRCL_AUTOSTART
#upradiosuser = bugsbunny
upradiostitle = Upmpdcli Radio List
#bbcuser = bugsbunny
#bbcprogrammedays = 30
#sclogfilename =
#scloglevel = 3
#scplaymethod = mpd
#schttpport = 8768
#scalsadevice = default
#sccvttype = SRC_SINC_FASTEST
#scusempdvolume = 0
#sc2mpd =
#screceiverstatefile =
#scplaymethod is alsa
#scstreamcodec =
#scsenderpath =
#scstreamscaled = 1
#scsendermpdport = 6700
#scripts_dir = /usr/share/upmpdcli/src_scripts
#scscriptgracesecs = 2

```
