### ISSUE TITLE
[Help] Trouble connecting to navidrome served at a subdirectory

### ISSUE THREAD

**Issue by alex-kronish** [GioF71/upmpdcli-docker#522]
I cannot for the life of me figure out what's going wrong here, if I try and access the DLNA server through a front end, I can see the Subsonic folder, then if I try and enter it, I get a message "Service login or communication failure"

In the docker logs I see alot of 405 Method Not Allowed's.

I'm not sure if maybe me hosting my navidrome instance at a subdirectory is what's tripping this up, I can't seem to find an example where that's the case. 

```
services:
  upmpdcli:
    image: giof71/upmpdcli
    container_name: flamedramon-upmpdcli
    user: 1000:110
    network_mode: 'host'
    restart: 'unless-stopped'
    environment:
       PORT_OFFSET: 2
       #RENDERER_MODE: "NONE"
       LOG_ENABLE: "yes"
       LOG_LEVEL: 2
       SUBSONIC_AUTOSTART: "yes"
       SUBSONIC_PORT: 443
       SUBSONIC_USER: "removed"
       SUBSONIC_PASSWORD: "removed"
       SUBSONIC_SERVER_SIDE_SCROBBLING: "yes"
       SUBSONIC_ENABLE_INTERNET_RADIOS: "yes"
       SUBSONIC_ENABLE: "yes"
       UPMPD_FRIENDLY_NAME: "flamedramon-dlna"
       SUBSONIC_BASE_URL: "https://flamedramon.my-reverse-proxy-host.us/navidrome/"
       #SUBSONIC_DOWNLOAD_PLUGIN: yes
       #SUBSONIC_PLUGIN_BRANCH: latest-subsonic
       #SUBSONIC_FORCE_CONNECTOR_VERSION: 0.3.1
    volumes:
      - /tools/upmpdcli/cache:/cache
      - /tools/upmpdcli/log:/log
```

**Comment by GioF71** [comment]
Hello, yes the problem is with the url with a directory, currently not supported. Should be easy to fix. Let me think about it.
Is there a change that you can configure a user for me so I can test, if the url is publicly accessible? If so, we can maybe connect on discord.
Not mandatory but would be helpful for my testing.

**Comment by GioF71** [comment]
Try this image: giof71/upmpdcli:edgefeature-f522b1-stable-full

Set:
SUBSONIC_BASE_URL: "https://flamedramon.my-reverse-proxy-host.us"
SUBSONIC_SERVER_PATH: "SUBSONIC_BASE_URL: "navidrome"

Let's hope I did it right.

**Comment by GioF71** [comment]
Hello, thank you, I noticed that ND_BASEURL but stubbornly a few hours ago, I wanted to configure the reverse with the path and couldn't make it work.
So now I am skipping the reverse proxy and upmpdcli is connecting to the regular 4533 port for this test.

So, I just tried to add ND_BASEURL=/navidrome to my navidrome compose file, then used the image I mentioned, and added SUBSONIC_SERVER_PATH: "navidrome" and it worked for me.

Can you post your compose file, and the container logs?
Thank yo

**Comment by GioF71** [comment]
In particular, please check that the variable SUBSONIC_BASE_URL does not end with a slash. For example considering your initial compose, it should be: https://flamedramon.my-reverse-proxy-host.us

**Comment by alex-kronish** [comment]
I think it was the base url ending with a slash - thanks for that tip. I removed it and it seems like it works now. Going to experiment a little with it later tonight, but at a glance it seems to be working.

I know most people set up their reverse proxies with subdirectories, but I like doing subdirectories for SSL simplicity reasons. So if someone comes looking for an answer for this in the future, my working docker compose now looks like:

```
services:
  upmpdcli:
    #image: giof71/upmpdcli
    image: giof71/upmpdcli:edgefeature-f522b1-stable-full
    container_name: flamedramon-upmpdcli
    user: 1000:110
    network_mode: 'host'
    restart: 'unless-stopped'
    environment:
       PORT_OFFSET: 2
       RENDERER_MODE: "NONE"
       LOG_ENABLE: "yes"
       LOG_LEVEL: 2
       SUBSONIC_AUTOSTART: "yes"
       SUBSONIC_PORT: 443
       SUBSONIC_USER: "removed"
       SUBSONIC_PASSWORD: "removed"
       SUBSONIC_SERVER_SIDE_SCROBBLING: "yes"
       SUBSONIC_ENABLE_INTERNET_RADIOS: "yes"
       SUBSONIC_ENABLE: "yes"
       UPMPD_FRIENDLY_NAME: "flamedramon-dlna"
       SUBSONIC_BASE_URL: "https://reverse-proxy-host.us"
       #SUBSONIC_DOWNLOAD_PLUGIN: yes
       #SUBSONIC_PLUGIN_BRANCH: latest-subsonic
       #SUBSONIC_FORCE_CONNECTOR_VERSION: 0.3.1
       SUBSONIC_SERVER_PATH: "navidrome"
    volumes:
      - /tools/upmpdcli/cache:/cache
      - /tools/upmpdcli/log:/log
```
